bn_api:
    key: "1VUTeJRnyZAqv1Rd8GvXALcOBLXOacqyIhepK3tjckS3YRiCgFB7SAW0koAkkLuj"
    secret: "zjWU4n4K0ZkxfO6VkM2snODxVDlLGvxvVGf5PT790STADOK3pLPSVxNqvFK3RGcf"
okx_api:
    key: "21669db0-a36f-4434-a81b-dec0c76e0fb9"
    secret: "1D34C6D0BAFD9CF88EF8B589720C92DC"
    passphrase: "Luckin8*"

alpha_params:
    alp_adx_stochrsi_dematr_sing: {'adx_len': 20, 'rsi_len': 47, 'kd': 8, 'dema_len': 21, 'atr_len': 12, 'atr_profit': 3, 'atr_loss': 4}
    alp_adx_stochrsi_dematr_multi: {'adx_len': 26, 'rsi_len': 14, 'kd': 5, 'dema_len': 15, 'atr_len': 57, 'atr_profit': 3, 'atr_loss': 4}
    alp_super_dema_bodyatr_multi: {'sptr_len': 45, 'sptr_k': 3.0, 'dema_len': 60, 'atr_len': 36, 'harvest_ratio': 1.8, 'retreat_ratio': 1.2}
    alp_super_dematr_multi: {'sptr_len': 39, 'sptr_k': 2.5, 'dema_len': 15, 'atr_len': 45, 'atr_profit': 3, 'atr_loss': 4}
