bn_api:
    key: "1VUTeJRnyZAqv1Rd8GvXALcOBLXOacqyIhepK3tjckS3YRiCgFB7SAW0koAkkLuj"
    secret: "zjWU4n4K0ZkxfO6VkM2snODxVDlLGvxvVGf5PT790STADOK3pLPSVxNqvFK3RGcf"
okx_api:
    key: "21669db0-a36f-4434-a81b-dec0c76e0fb9"
    secret: "1D34C6D0BAFD9CF88EF8B589720C92DC"
    passphrase: "Luckin8*"

backpack_api:
    key: "MvRvB3dAF+ObKSjrLbypJZ/Kd485RZ88ZrnqoLShCeI="
    secret: "gM3WctyAMFbDLBtYC911nNH6lCM878ZDvKXI83gdV3Y="

alpha_params:
    alp_adx_stochrsi_dematr_multi: {'adx_len': 57, 'rsi_len': 33, 'stoch_len': 27, 'kd': 3, 'dema_len': 21, 'atr_profit': 5, 'atr_loss': 5}
    alp_linbo_dempact: {'swing': 90, 'reset': 281, 'slope': 1.0, 'profit_pct': 0.038, 'loss_pct': 0.002}
    alp_super_openatr: {'sptr_len': 90, 'sptr_k': 4.0, 'atr_profit': 16, 'atr_loss': 5}