bn_api:
    key: "1VUTeJRnyZAqv1Rd8GvXALcOBLXOacqyIhepK3tjckS3YRiCgFB7SAW0koAkkLuj"
    secret: "zjWU4n4K0ZkxfO6VkM2snODxVDlLGvxvVGf5PT790STADOK3pLPSVxNqvFK3RGcf"
okx_api:
    key: "21669db0-a36f-4434-a81b-dec0c76e0fb9"
    secret: "1D34C6D0BAFD9CF88EF8B589720C92DC"
    passphrase: "Luckin8*"

backpack_api:
    key: "MvRvB3dAF+ObKSjrLbypJZ/Kd485RZ88ZrnqoLShCeI="
    secret: "gM3WctyAMFbDLBtYC911nNH6lCM878ZDvKXI83gdV3Y="

discord_webhook:
    url: "https://discord.com/api/webhooks/1241409376376455179/kbukhAxvkxUpjoHgfbG8uCtHMWjkk_8qDuit-TRVbxYFDaaDrSfrb9Od3di1Aa-TL99D"

alpha_params:
    alp_adx_stochrsi_dematr_multi: {'adx_len': 57, 'rsi_len': 33, 'stoch_len': 27, 'kd': 3, 'dema_len': 21, 'atr_profit': 5, 'atr_loss': 5}
    alp_linbo_dempact: {'swing': 39, 'reset': 280, 'slope': 0.8, 'profit_pct': 0.002, 'loss_pct': 0.006}
    alp_super_openatr: {'sptr_len': 12, 'sptr_k': 2.5, 'vol_len': 36, 'atr_profit': 13, 'atr_loss': 6}
    alp_adx_stochrsi_openatr: {'adx_len': 69, 'rsi_len': 90, 'stoch_len': 102, 'kd': 5, 'vol_len': 56, 'atr_profit': 8, 'atr_loss': 8}